[profile.default]
src = "src"
out = "out"
libs = [
    "lib",
]

allow_paths = [
    "../../primitives",
    "src/compression",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
